"use client";
import { useEffect, useState } from "react";
import type { Item, SiteData } from "@/lib/types";

const empty: SiteData = { settings: { teamName: "", intro: "", headline: "", description: "", heroAssetUrl: null }, projects: [], members: [], assets: [] };

export default function AdminPage() {
  const [data, setData] = useState<SiteData>(empty);
  const [kind, setKind] = useState<"projects" | "members">("projects");
  const [message, setMessage] = useState("불러오는 중…");
  const [draft, setDraft] = useState({ name: "", isVisible: true });
  const load = async () => { const res = await fetch("/api/admin/content"); if (res.status === 401) { location.href = "/admin/login"; return; } const json = await res.json(); setData(json); setMessage("저장된 변경사항"); };
  useEffect(() => { load().catch(() => setMessage("데이터를 불러오지 못했습니다.")); }, []);
  const saveSettings = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); const res = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setMessage(res.ok ? "사이트 정보를 저장했습니다." : "저장에 실패했습니다."); await load(); };
  const add = async (event: React.FormEvent) => { event.preventDefault(); if (!draft.name.trim()) return; const res = await fetch(`/api/admin/${kind}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); if (res.ok) { setDraft({ name: "", isVisible: true }); setMessage("항목을 추가했습니다."); await load(); } };
  const remove = async (item: Item) => { if (!confirm(`${item.name}을 삭제할까요?`)) return; await fetch(`/api/admin/${kind}/${item.id}`, { method: "DELETE" }); await load(); };
  return <div className="admin-shell"><header className="admin-top"><a className="wordmark" href="/">REMO<span className="star">✳</span></a><span className="admin-note">REMO STUDIO / 관리자</span><a href="/api/auth/logout">로그아웃</a></header><main className="admin-main"><div className="admin-intro"><div><small>WORKSPACE</small><h1>팀 콘텐츠 관리</h1><p>프로젝트, 구성원, 홈페이지 소개 정보를 Neon에 저장합니다.</p></div><span className="admin-state">{message}</span></div><div className="admin-grid"><section className="admin-card"><h2>기본 정보</h2><form onSubmit={saveSettings}>{[["teamName","팀 이름"],["intro","팀 소개"],["headline","메인 제목"]].map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={data.settings[key as keyof typeof data.settings] || ""}/></label>)}<label>소개 문구<textarea name="description" defaultValue={data.settings.description}/></label><button className="admin-button" type="submit">정보 저장</button></form></section><section className="admin-card"><div className="admin-card-title"><h2>{kind === "projects" ? "프로젝트" : "구성원"}</h2><div className="tabs"><button className={kind === "projects" ? "active" : ""} onClick={() => setKind("projects")}>프로젝트</button><button className={kind === "members" ? "active" : ""} onClick={() => setKind("members")}>구성원</button></div></div><form className="add-row" onSubmit={add}><input aria-label="새 항목 이름" value={draft.name} onChange={e => setDraft({...draft,name:e.target.value})} placeholder={kind === "projects" ? "프로젝트 이름" : "구성원 이름"}/><button className="admin-button" type="submit">추가</button></form><ul className="admin-list">{data[kind].map(item=><li key={item.id}><span><b>{item.name}</b><small>{item.isVisible ? "홈페이지에 표시" : "숨김"}</small></span><button className="delete" onClick={() => remove(item)} aria-label={`${item.name} 삭제`}>삭제</button></li>)}</ul></section></div><p className="admin-footnote">관리자 계정: remo_admin · 인증·DB 연결은 환경변수와 Neon 스키마 설정 후 활성화됩니다.</p></main></div>;
}
